//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBScript.Parser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VBSyntaxErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VBSyntaxErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VBScript.Parser.VBSyntaxErrorMessages", typeof(VBSyntaxErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory.
        /// </summary>
        internal static string _1001 {
            get {
                return ResourceManager.GetString("1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error.
        /// </summary>
        internal static string _1002 {
            get {
                return ResourceManager.GetString("1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;:&apos;.
        /// </summary>
        internal static string _1003 {
            get {
                return ResourceManager.GetString("1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;(&apos;.
        /// </summary>
        internal static string _1005 {
            get {
                return ResourceManager.GetString("1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;)&apos;.
        /// </summary>
        internal static string _1006 {
            get {
                return ResourceManager.GetString("1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;]&apos;.
        /// </summary>
        internal static string _1007 {
            get {
                return ResourceManager.GetString("1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected identifier.
        /// </summary>
        internal static string _1010 {
            get {
                return ResourceManager.GetString("1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;=&apos;.
        /// </summary>
        internal static string _1011 {
            get {
                return ResourceManager.GetString("1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;If&apos;.
        /// </summary>
        internal static string _1012 {
            get {
                return ResourceManager.GetString("1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;To&apos;.
        /// </summary>
        internal static string _1013 {
            get {
                return ResourceManager.GetString("1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;End&apos;.
        /// </summary>
        internal static string _1014 {
            get {
                return ResourceManager.GetString("1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;Function&apos;.
        /// </summary>
        internal static string _1015 {
            get {
                return ResourceManager.GetString("1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;Sub&apos;.
        /// </summary>
        internal static string _1016 {
            get {
                return ResourceManager.GetString("1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;Then&apos;.
        /// </summary>
        internal static string _1017 {
            get {
                return ResourceManager.GetString("1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;Wend&apos;.
        /// </summary>
        internal static string _1018 {
            get {
                return ResourceManager.GetString("1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;Loop&apos;.
        /// </summary>
        internal static string _1019 {
            get {
                return ResourceManager.GetString("1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;Next&apos;.
        /// </summary>
        internal static string _1020 {
            get {
                return ResourceManager.GetString("1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;Case&apos;.
        /// </summary>
        internal static string _1021 {
            get {
                return ResourceManager.GetString("1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;Select&apos;.
        /// </summary>
        internal static string _1022 {
            get {
                return ResourceManager.GetString("1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected expression.
        /// </summary>
        internal static string _1023 {
            get {
                return ResourceManager.GetString("1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected statement.
        /// </summary>
        internal static string _1024 {
            get {
                return ResourceManager.GetString("1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of statement.
        /// </summary>
        internal static string _1025 {
            get {
                return ResourceManager.GetString("1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected integer constant.
        /// </summary>
        internal static string _1026 {
            get {
                return ResourceManager.GetString("1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;While&apos; or &apos;Until&apos;.
        /// </summary>
        internal static string _1027 {
            get {
                return ResourceManager.GetString("1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;While&apos;, &apos;Until&apos; or end of statement.
        /// </summary>
        internal static string _1028 {
            get {
                return ResourceManager.GetString("1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;With&apos;.
        /// </summary>
        internal static string _1029 {
            get {
                return ResourceManager.GetString("1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier too long.
        /// </summary>
        internal static string _1030 {
            get {
                return ResourceManager.GetString("1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number.
        /// </summary>
        internal static string _1031 {
            get {
                return ResourceManager.GetString("1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character.
        /// </summary>
        internal static string _1032 {
            get {
                return ResourceManager.GetString("1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string constant.
        /// </summary>
        internal static string _1033 {
            get {
                return ResourceManager.GetString("1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated comment.
        /// </summary>
        internal static string _1034 {
            get {
                return ResourceManager.GetString("1034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid use of &apos;Me&apos; keyword.
        /// </summary>
        internal static string _1037 {
            get {
                return ResourceManager.GetString("1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;loop&apos; without &apos;do&apos;.
        /// </summary>
        internal static string _1038 {
            get {
                return ResourceManager.GetString("1038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;exit&apos; statement.
        /// </summary>
        internal static string _1039 {
            get {
                return ResourceManager.GetString("1039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;for&apos; loop control variable.
        /// </summary>
        internal static string _1040 {
            get {
                return ResourceManager.GetString("1040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name redefined.
        /// </summary>
        internal static string _1041 {
            get {
                return ResourceManager.GetString("1041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be first statement on the line.
        /// </summary>
        internal static string _1042 {
            get {
                return ResourceManager.GetString("1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign to non-ByVal argument.
        /// </summary>
        internal static string _1043 {
            get {
                return ResourceManager.GetString("1043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use parentheses when calling a Sub.
        /// </summary>
        internal static string _1044 {
            get {
                return ResourceManager.GetString("1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected literal constant.
        /// </summary>
        internal static string _1045 {
            get {
                return ResourceManager.GetString("1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;In&apos;.
        /// </summary>
        internal static string _1046 {
            get {
                return ResourceManager.GetString("1046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;Class&apos;.
        /// </summary>
        internal static string _1047 {
            get {
                return ResourceManager.GetString("1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be defined inside a Class.
        /// </summary>
        internal static string _1048 {
            get {
                return ResourceManager.GetString("1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Let or Set or Get in property declaration.
        /// </summary>
        internal static string _1049 {
            get {
                return ResourceManager.GetString("1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;Property&apos;.
        /// </summary>
        internal static string _1050 {
            get {
                return ResourceManager.GetString("1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of arguments must be consistent across properties specification.
        /// </summary>
        internal static string _1051 {
            get {
                return ResourceManager.GetString("1051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have multiple default property/method in a Class.
        /// </summary>
        internal static string _1052 {
            get {
                return ResourceManager.GetString("1052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class initialize or terminate do not have arguments.
        /// </summary>
        internal static string _1053 {
            get {
                return ResourceManager.GetString("1053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property set or let must have at least one argument.
        /// </summary>
        internal static string _1054 {
            get {
                return ResourceManager.GetString("1054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected &apos;Next&apos;.
        /// </summary>
        internal static string _1055 {
            get {
                return ResourceManager.GetString("1055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Default&apos; can be specified only on &apos;Property&apos; or &apos;Function&apos; or &apos;Sub&apos;.
        /// </summary>
        internal static string _1056 {
            get {
                return ResourceManager.GetString("1056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Default&apos; specification must also specify &apos;Public&apos;.
        /// </summary>
        internal static string _1057 {
            get {
                return ResourceManager.GetString("1057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Default&apos; specification can only be on Property Get.
        /// </summary>
        internal static string _1058 {
            get {
                return ResourceManager.GetString("1058", resourceCulture);
            }
        }
    }
}
